version: "5.1.4"

services:
  ordersservice:
    image: danielmusselwhite/commercefabric_order_microservice:1.0.0
    container_name: ordersservice
    build:
      context: .
      dockerfile: OrdersMicroservice.API/Dockerfile
    ports:
      - "7070:8080"
    networks:
      - commercefabric-network
    depends_on:
      - mongodb-orderservice

  mongodb-orderservice:
    image: mongo:latest
    container_name: mongodb-orderservice
    ports:
      - "27017:27017"
    volumes:
      - ./Resources/docker/mongodb-init:/docker-entrypoint-initdb.d:ro
    networks:
      - commercefabric-network
    restart: unless-stopped